#!/bin/bash

/bin/rm /cust/jboss-eap-6.3/standalone1/log/*
/bin/rm /cust/jboss-eap-6.3/standalone2/log/*

/bin/rm /cust/jboss-eap-6.3/standalone1/log/default-host/*
/bin/rm /cust/jboss-eap-6.3/standalone2/log/default-host/*
