domains:
  - name: univision23.com
  - name: univisionaustin.com
  - name: galavision.com
  - name: wado1280am.com
  - name: x963fm.com
  - name: 927nuevayork.com
  - name: univisionnuevayork.com
  - name: 941dallas.com
  - name: 1079dallas.com
  - name: latinomix991.com
  - name: univisiondallas.com
  - name: 1059dallas.com
  - name: 1063masvariedad.com
  - name: latinomix1003.com
  - name: univisionarizona.com
  - name: 1013nuevomexico.com
  - name: iloveklove.com
  - name: 1019losangeles.com
  - name: recuerdola.com
  - name: univision34.com
