domains:
  - name: 1059dallas.com
  - name: 1063masvariedad.com
  - name: 1079dallas.com
  - name: 927nuevayork.com
  - name: 941dallas.com
  - name: galavision.com
  - name: latinomix1003.com
  - name: latinomix991.com
  - name: recuerdola.com
  - name: univisionarizona.com
  - name: univisionaustin.com
  - name: univisiondallas.com
  - name: univisionnuevayork.com
  - name: wado1280am.com
  - name: x963fm.com
  - name: 1003phoenix.com
  - name: 1051nuevomexico.com
  - name: 1059phoenix.com
  - name: 1063recuerdo.com
  - name: 1079hothits.com
  - name: 2hot4dfw.com
  - name: 927laquebuena.com
  - name: 991dallas.com
  - name: amordallas.com
  - name: bigd1059.com
  - name: bigd1079.com
  - name: bigdhot.com
  - name: copaunivisiondallas.com
  - name: copaunivisionla.com
  - name: copaunivisionlosangeles.com
  - name: copaunivisionnewyork.com
  - name: copaunivisionnuevayork.com
  - name: copaunivisionny.com
  - name: copaunivisionphoenix.com
  - name: d1059.com
  - name: d1059fm.com
  - name: d1079.com
  - name: dallas1059.com
  - name: dallas1079.com
  - name: dallas49.com
  - name: dfw1079.com
  - name: dfwishot.com
  - name: dtownhot.com
  - name: gethotindfw.com
  - name: hot1079dallas.com
  - name: hot1079dfw.com
  - name: hotdallas1079.com
  - name: hothits1079.com
  - name: hotinbigd.com
  - name: hotindtown.com
  - name: hottesthits1079.com
  - name: kess1270.com
  - name: kjfa.com
  - name: klove1029.com
  - name: la1019.com
  - name: la1059.com
  - name: lacalle1079.com
  - name: lacalleny.com
  - name: lajefa1013.com
  - name: lajefa991.com
  - name: lajefadallas.com
  - name: lakalle1003.com
  - name: lakalle1079.com
  - name: lakalle927.com
  - name: lakalle983fm.com
  - name: lakalledfw.com
  - name: lakalleny.com
  - name: laquebuena927.com
  - name: laquebuena991.com
  - name: laquebuenanewyork.com
  - name: luisjimenez.com
  - name: myhotdfw.com
  - name: mykalleny.com
  - name: newyork41.com
  - name: newyork67.com
  - name: newyork68.com
  - name: nueva1019.com
  - name: nueva1059.com
  - name: onhot1079.com
  - name: onhotdfw.com
  - name: ourhot1079.com
  - name: ourhotdfw.com
  - name: quebuenanewyork.com
  - name: radioh20.com
  - name: radioh20dfw.com
  - name: radioh2odallas.com
  - name: recuerdo1063.com
  - name: recuerdo983.com
  - name: recuerdodallas.com
  - name: recuerdophoenix.com
  - name: recuerdos983.com
  - name: recuerdos993.com
  - name: recuerdosphoenix.com
  - name: telefuturalosangeles.com
  - name: telefuturanewyork.com
  - name: univisiondfw.com
  - name: univisionnewyork.com
  - name: univisionny.com
  - name: univisionphoenix.com
  - name: univisiony.com
  - name: unuevayork.com
  - name: uvn34.com
  - name: wxtv-tv.com
  - name: wxtv.tv
  - name: univision23.com
  - name: iloveklove.com
