domains:
  - name: 1031chicago.com
  - name: 1043austin.com
  - name: 1051chicago.com
  - name: 1077masvariedad.com
  - name: 935chicago.com
  - name: amor1067.com
  - name: amor1075fm.com
  - name: copaunivisionaustin.com
  - name: copaunivisionchicago.com
  - name: copaunivisionmiami.com
  - name: elsancho1003.com
  - name: elsanchoaustin.com
  - name: jefaatx.com
  - name: jefaaustin.com
  - name: kakw.tv
  - name: kaq105.com
  - name: kq105.com
  - name: lajefaatx.com
  - name: lajefaaustin.com
  - name: miami23.com
  - name: miami69.com
  - name: noche106.com
  - name: noches106.com
  - name: pasion1067.com
  - name: pasionchicago.com
  - name: passion1067.com
  - name: radiomambi710.com
  - name: radioreloj580.com
  - name: recuerdo1077.com
  - name: recuerdos1077.com
  - name: sanchoatx.com
  - name: sanchoaustin.com
  - name: telefuturamiami.com
  - name: telefuturapr.com
  - name: telefuturapuertorico.com
  - name: univisionaustin.com
  - name: univisionchicago.com
  - name: univisionmiami.com
  - name: univisionpuertorico.com
  - name: wamr.com
  - name: waqi.com
  - name: wgbo-tv.com
  - name: wgbo.com
  - name: wgbo.tv
  - name: wgbo66.com
  - name: wltv-tv.com
  - name: wltv.tv
  - name: wltv23.com
  - name: wqba.com
  - name: wrto.com
