domains:
  - name: 1019elsancho.com
  - name: 1019lajefa.com
  - name: 1019lanueva.com
  - name: 1019losangeles.com
  - name: 1020am.com
  - name: 1029klove.com
  - name: 1029masvariedad.com
  - name: 1035lasvegas.com
  - name: 1035vegas.com
  - name: 1039masvariedad.com
