version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/before.sh
  AfterInstall:
    - location: scripts/after.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/started.sh
      timeout: 3600
  ValidateService:
    - location: scripts/validate.sh
      timeout: 3600
      runas: root
